In [1]:
import numpy as np
import pandas as pd
import numpy_financial as npf
import pandas_datareader as pdr

In [9]:
def risk(coeff):
    for i in range(len(coeff)):
        if coeff[i]>0:
            print((i),": a risk-averse investor")
        elif coeff[i]==0:
            print((i),": a risk-neutral investor")
        else:
            print((i),": a risk lover")

In [10]:
risk([2,4,0,5,-1])

0 : a risk-averse investor
1 : a risk-averse investor
2 : a risk-neutral investor
3 : a risk-averse investor
4 : a risk lover


In [21]:
def balance1(a,b,i):
    balance=a
    while balance<b:
        balance+=100+balance*(i)
    return balance

In [22]:
balance1(0,1000,0.1)

1143.5888099999997

In [24]:
def balance2(a,b,i):
    balance=balance1(a,b,i)
    if balance>1000:
         x="the final balance is above $1000"
    elif balance==1000:
         x="the final balance is equal to $1000"
    else:
         x="the final balance is below $1000"
    return x

In [25]:
balance2(0,1000,0.1)

'the final balance is above $1000'

In [28]:
def balance3(a,b,i):
    x=a
    while x<b:
        x+=100+x*(i)
    if x>1000:
        y="the final balance is above $1000"
    elif x==1000:
        y="the final balance is equal to $1000"
    else:
        y="the final balance is below $1000"
    return y

In [30]:
balance3(0,1000,0.1)

'the final balance is above $1000'

In [31]:
cf=[1000,1000,1000,1000,1000]
cf

[1000, 1000, 1000, 1000, 1000]

In [32]:
pv=np.ones(5)
pv

array([1., 1., 1., 1., 1.])

In [33]:
np.random.seed(0)
r=np.random.normal(0.1,0.01,5)
r

array([0.11764052, 0.10400157, 0.10978738, 0.12240893, 0.11867558])

In [34]:
for i in range(len(cf)):
    pv[i] = (cf[i])/(1+r[i])**(i+1)
print(pv)

[894.74207405 820.46605232 731.61172078 630.07978116 570.79375274]


In [35]:
sum(pv)

3647.693381045227

In [37]:
def pv_mul(cf):
    n=len(cf)
    pv=np.ones(n)
    np.random.seed(0)
    r=np.random.normal(0.1,0.01,n)
    for i in range(n):
        pv[i] = (cf[i])/(1+r[i])**(i+1)
    return sum(pv) 

In [38]:
pv_mul([1000,1000,1000,1000,1000])


3647.693381045227

In [39]:
l1=['INTC','IBM','FB']

In [40]:
df=pdr.get_data_yahoo(l1, start= '09/21/2020', end= '09/25/2020')['Adj Close']
df.head(10)

Symbols          INTC         IBM          FB
Date                                         
2020-09-21  47.749672  106.606140  248.149994
2020-09-22  47.970551  106.836617  254.750000
2020-09-23  46.885334  105.347252  249.020004
2020-09-24  47.211861  104.691208  249.529999
2020-09-25  47.960945  105.453621  254.820007

In [41]:
df['IBM'].mean()

105.78696746826172

In [42]:
df[df['IBM']>df['IBM'].mean()]

Symbols          INTC         IBM          FB
Date                                         
2020-09-21  47.749672  106.606140  248.149994
2020-09-22  47.970551  106.836617  254.750000

In [43]:
df.to_csv('df_l1.csv')

In [44]:
df2=pd.read_csv('df_l1.csv')
df2

Date       INTC         IBM          FB
0  2020-09-21  47.749672  106.606140  248.149994
1  2020-09-22  47.970551  106.836617  254.750000
2  2020-09-23  46.885334  105.347252  249.020004
3  2020-09-24  47.211861  104.691208  249.529999
4  2020-09-25  47.960945  105.453621  254.820007

In [45]:
df2.tail(2)

Date       INTC         IBM          FB
3  2020-09-24  47.211861  104.691208  249.529999
4  2020-09-25  47.960945  105.453621  254.820007