## ML Project 1

In [24]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
y_val=np.load("y_val.npy")
y_train= np.load("y_train.npy")

x_val= np.load("X_val.npy")
x_train= np.load("X_train.npy")

In [11]:
np.shape(x_train)

(8000, 20000)

In [16]:
np.column_stack([ones_val, x_val])

array([[4.77168202e-01, 1.04365945e-01, 4.38000679e-01, ...,
        1.58722294e-04, 1.31738849e-03, 7.95907855e-01],
       [7.34000802e-01, 7.93504715e-02, 8.36406231e-01, ...,
        2.51015136e-03, 2.93268226e-02, 5.45742102e-02],
       [1.57281280e-01, 4.47364092e-01, 2.81550169e-01, ...,
        5.26649177e-01, 2.36357388e-04, 7.64917552e-01],
       ...,
       [3.78791094e-01, 7.55949020e-02, 4.04572010e-01, ...,
        6.03047788e-01, 3.21115530e-03, 7.69789100e-01],
       [3.60332727e-02, 5.84659100e-01, 2.73674607e-01, ...,
        2.13794038e-01, 3.00218072e-02, 1.21923476e-01],
       [6.21727705e-02, 7.54159808e-01, 9.73835111e-01, ...,
        4.30405699e-03, 5.51002264e-01, 7.08560884e-01]], dtype=float32)

In [17]:
np.column_stack([ones_val, x_val])

array([[1.00000000e+00, 4.77168202e-01, 1.04365945e-01, ...,
        1.58722294e-04, 1.31738849e-03, 7.95907855e-01],
       [1.00000000e+00, 7.34000802e-01, 7.93504715e-02, ...,
        2.51015136e-03, 2.93268226e-02, 5.45742102e-02],
       [1.00000000e+00, 1.57281280e-01, 4.47364092e-01, ...,
        5.26649177e-01, 2.36357388e-04, 7.64917552e-01],
       ...,
       [1.00000000e+00, 3.78791094e-01, 7.55949020e-02, ...,
        6.03047788e-01, 3.21115530e-03, 7.69789100e-01],
       [1.00000000e+00, 3.60332727e-02, 5.84659100e-01, ...,
        2.13794038e-01, 3.00218072e-02, 1.21923476e-01],
       [1.00000000e+00, 6.21727705e-02, 7.54159808e-01, ...,
        4.30405699e-03, 5.51002264e-01, 7.08560884e-01]], dtype=float32)

In [18]:
ones_train=np.ones_like(y_train)


In [19]:
ones_val= np.ones_like(y_val)

In [20]:
X_train= np.column_stack([ones_train, x_train])
X_val= np.column_stack([ones_val, x_val])

In [21]:
np.shape(X_train)

(8000, 20001)

In [ ]:
## Finding optimized λ value

def solve(λ):
    
    I= np.eye(X_train.shape[1])
    θ= np.linalg.solve(X_train.T @ X_train + λ * I, X_train.T @ y_train)
    
    prediction= X_val @ θ
    e= prediction - y_val
    
    MSE_val= (e.T @ e)/len(X_train)
    return MSE_val

In [ ]:
possible_λ = [0.01, 0.1, 1, 10, 100]

for λ in possible_λ:
    MSE_val = solve(λ)
    print(MSE_val)

In [11]:
λ= 100
I= np.eye(X_train.shape[1])
θ= np.linalg.solve(X_train.T @ X_train + λ * I, X_train.T @ y_train)

In [13]:
θ


array([ 0.88265261,  0.36476647,  0.21471551, ..., -0.01309184,
       -0.0503789 , -0.06815213])

In [12]:
# Prediction Function

def f(X):
    prediction= X @ θ
    return prediction